### ISSUE TITLE
Version 2.7 offline build kernel for gfx1100 not compatible with OpenCL runtime

### ISSUE THREAD

**Issue by Lolliedieb** [GPUOpen-Tools/radeon_gpu_analyzer#104]
Dear rga development team,

I do not own a new RX7900 generation GPU yet, but needed to compile an application for a customer of mine. Therefore I did run RGA 2.7 in graphics mode, loaded my kernel there and done the analysis. At the end I grabbed the generated codeobject and did load as in a binary kernel into my application. This process is usually working perfectly for gfx103x and gfx101x devices.
Unfortunately the OpenCL runtime refused to run on this kernel. clCreateProgramWithBinary did work without prompting me an error message and clbuildProgram, too, but clcreatekernel exited with an error code -6. 

After this requested access to the machine in a secure connection and did run my kernel in text form just fine. Afterwards I did extract that binary kernel and included this into my application: also, this was working just fine. So it has to be a kind of format issue with what is produced by RGA. 

The testing machine is running a 7900XT on Ubuntu 20.04 and amdgpu-pro 22.40.6 with reported OpenCL version 3513.0.
The RGA used was 2.7 both on Ubuntu 20.04, 22.04 and Windows 10. Note that the driver used in Windows 10 was one from the 22.11 series. I am aware, that the release page states
 
`For AMD Radeon™ RX 7000 Series GPUs, make sure you have the [Adrenalin 22.12.1 for RX7000 Series Graphics with Radeon Developer Tool Suite Support](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-12-1-rx7900-rgp-support) driver or newer installed.`

but considering that this driver does not support older architectures and I want to run RGA to offline build for the new ones in absence of owning one ... if its a joke, then I do not find it funny at all. 

I'm sorry if the comment is a bit snarky, but it would be really nice if the developer tools would allow reliable offline building at the beginning of a new architecture. 

Ps: it might be related, but i have the same problem with offline builds when using clang-15 from the current rocm 5.4 repository - also here it looks like gfx1100 is supported without problems and there are no error messages or similar, but the kernel can't be used as offline kernel exactly like in rga unfortunately.

**Comment by Lolliedieb** [comment]
So - we have a bigger incompatibility between the latest releases of this and the latest driver that breaks one of the core functionalities when not self owing a card to compile binary kernels - and in two weeks no one cares?

**Comment by AmitBM** [comment]
Hi Lolliedieb,

Thanks for reporting this.

1. RGA's offline modes do not depend on the driver as the "System Requirements" section of the release notes mentions (please see the [RGA 2.7 Release Notes document](https://github.com/GPUOpen-Tools/radeon_gpu_analyzer/releases/download/2.7/RGA-2.7-ReleaseNotes.pdf) for more details). 
2. The fact that you observe this issue with ROCm 5.4 implies that this is a ROCm compiler/runtime issue - did you create a GitHub issue on the ROCm repository as well? Anyway, we will make the relevant team aware of this and get back to you when we have more details.

**Comment by AmitBM** [comment]
Hi @Lolliedieb,

This was indeed a compiler issue. 

Can you please confirm that the issue is fixed when you build your code using RGA 2.7.1 (released last week)?

On **Linux** -
both GFX9 and RDNA (GFX10 and on) Code Object binaries are expected to be loaded successfully.

On **Windows** - 

Code Object files that were built for RDNA architectures (GFX10 and on) should be loaded successfully as-is.
To load Code Objects that were built for Vega architectures (GFX9), please set the following environment variable for the process that attempts to load the binary:
 `GPU_ENABLE_LC=1` (set GPU_ENABLE_LC to 1).

**Comment by Lolliedieb** [comment]
Came back here after a while, indeed newer versions have this fixed. Thanks!
