### ISSUE TITLE
Can't use empty InputLayout and RTVFormats in graphics pipeline

### ISSUE THREAD

**Issue by TIMONz1535** [GPUOpen-Tools/radeon_gpu_analyzer#106]
1) Some post effects use an **Empty vertex format**. An empty vertex buffer is passed to the Draw input, and the vertex shader is called only with system generated inputs, like **SV_VertexID, SV_InstanceID**.
Well, I can't specify an empty **InputLayout** in the **.gpso** file because it gives an error `Error: number of input layout element items must be non-zero.`.
But at the same time, all this works correctly in hardware. I think this is a common feature on GPUs.

2) Also, when you draw a **Depth pass**, you do not bind any render targets (**RTVFormats**), you bind only the **Depth buffer** (DSV) like `DXGI_FORMAT_D24_UNORM_S8_UINT` or `DXGI_FORMAT_D32_FLOAT_S8X24_UINT`. Well, I can't specify an empty **RTVFormats** in the **.gpso**. The graphic pipeline can't be compiled.

```
Windows 10 Pro 21H2 (19044.2486)
DirectX 12 (Radeon RX 580 Series or offline mode)
Radeon GPU Analyzer Version: 2.7.0.129
```

**Comment by AmitBM** [comment]
Hi @TIMONz1535,

Thanks for reporting this issue.

Can you please share the shaders (+ root signature) and .gpso file you are using and expect to compile successfully?

**Comment by AmitBM** [comment]
Hi @TIMONz1535,

Thanks again for reporting this and providing repro files.

RGA v2.7.1 (released last week) should contain a fix for this issue.

Can you please confirm that this is resolved for you with the latest release?

**Comment by TIMONz1535** [comment]
I can confirm that everything is working now, thanks!
