### ISSUE TITLE
v2.0.1 rocm-cl compiler bug?

### ISSUE THREAD

**Issue by dooglz** [GPUOpen-Tools/radeon_gpu_analyzer#34]
Using pr rebuilt linux/windows binaries (2.0.1 d730d0b) I'm having trouble compiling a simple .cl program.
Command:
**rga -s rocm-cl --isa output/isa3.text hello.cl**

Program:

```
__kernel void HelloWorld(__global char* data)
{
data[0] = 'H';
data[1] = 'e';
data[2] = 'l';
data[3] = 'l';
data[4] = 'o';
data[5] = ',';
data[6] = ' ';
data[7] = 'W';
data[8] = 'o';
data[9] = 'r';
data[10] = 'l';
data[11] = 'd';
data[12] = '!';
data[13] = 'H';
}
```

I get the same error on Windows and Ubuntu 18.04.
Interestingly, if you edit the last line to be data[14] or remove it. It compiles :confused:
This code does compile on RGA rga-2.0.1193 (tested on linux) and 1.1 (tested on windows) 

[hello.cl.txt](https://github.com/GPUOpen-Tools/RGA/files/2472620/hello.cl.txt)
[error.txt](https://github.com/GPUOpen-Tools/RGA/files/2472610/error.txt)
[hello-f4d1ea.sh.txt](https://github.com/GPUOpen-Tools/RGA/files/2472618/hello-f4d1ea.sh.txt)
[hello-f4d1ea.cl.txt](https://github.com/GPUOpen-Tools/RGA/files/2472619/hello-f4d1ea.cl.txt)

**Comment by AmitBM** [comment]
Hi dooglz,

This is indeed a bug in the Lightning Compiler package which is bundled with RGA 2.1. We will update the compiler package in future releases, and hopefully the updated package would contain a fix for your issue.

In the meantime, you can use the Alternative Compiler feature and have RGA 2.1 reference the 2.0.1193 compiler or a local build of the compiler.

To do that. you should provide RGA with the following additional options:
--compiler-bin <folder> (e.g. 2.0/bin/x64/ROCm/OpenCL/bin)
--compiler-inc <folder> (e.g. 2.0/bin/x64/ROCm/OpenCL/include)
--compiler-lib <folder> (e.g. 2.0/bin/x64/ROCm/OpenCL/lib/bitcode)

For more details, run rga -s rocm-cl -h

**Comment by dooglz** [comment]
Is it possible for me to compile a newer version of the Lightning compiler myself?

i.e would it just be a case of building [RadeonOpenCompute/llvm](https://github.com/RadeonOpenCompute/llvm) / clang ...etc.

if so, would appreciate a point int he right direction, or is this based on private code?

**Comment by AmitBM** [comment]
Hi dooglz, 

You would want to look at the amd-common branch of llvm, clang and lld:
https://github.com/RadeonOpenCompute/llvm
https://github.com/RadeonOpenCompute/clang
https://github.com/RadeonOpenCompute/lld

More information can be found here - 
https://github.com/RadeonOpenCompute/llvm/blob/amd-common/README.txt
https://github.com/RadeonOpenCompute/llvm/blob/amd-common/docs/GettingStarted.rst
https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/README.md
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/master/README.md

**Comment by AmitBM** [comment]
Hi dooglz,

The latest release (RGA 2.5) ships with an updated version of the Lightning Compiler, which fixes this issue.
