### ISSUE TITLE
Please don't deprecate Offline Mode

### ISSUE THREAD

**Issue by Steve132** [GPUOpen-Tools/radeon_gpu_analyzer#56]
The README.md says this:

> Note that the this mode is about to be removed from RGA. To ensure that the results that RGA provides are accurate and reflect the real-life case, please use the new Vulkan live driver mode (which is also supported in the GUI application).

> AMD Radeon Adrenalin Software must be installed to run this tool (for all modes except for Offline Vulkan and ROCm OpenCL).

This tool is invaluable to debug shaders and the way the code will generate for SPIRV on various architectures.  If primary shader development is being done on an nvidia workstation, deprecating this mode will make it essentially impossible to debug shaders for AMD platforms, making this tool useless and discouraging optimization for performance on AMD platforms unless the entire development environment is on AMD workstations.   Similar complaints apply to the AMD Radeon Adrenalin Software (which cannot be applied on headless or intel or nvidia workstations).    

While I don't develop on an AMD workstation, I'd like my code to be compliant and performant on those platforms, which requires some way of inspecting the shader ISA, even if I'm not currently running the AMD driver on AMD hardware in my development environment...  So therefore it's in AMD's best interest for development targeting of their platform that this is still possible, and this tool is the only way I know of to accomplish it.

**Comment by AmitBM** [comment]
Hi Steve132,

Thank you for your comment. 

Please note that RGA is packaged with the AMD Vulkan driver to enable you on machines that do not have an AMD device or driver installed. When you compile in Vulkan mode, RGA would first try to use the system driver. If that does not work, it would fall back to using the packaged driver. Only in the case that the compilation with the packaged driver fails as well, RGA would fall back to using offline mode. If the fallback to offline mode happens, it probably means that the pipeline state that was provided does not match the shaders or is missing some critical data. 

In both fallback cases you should see a relevant warning message in the build log notifying you of what happened. Are you seeing a different behavior?

**Comment by Steve132** [comment]
> AMD Radeon Adrenalin Software must be installed to run this tool (for all modes except for Offline Vulkan and ROCm OpenCL).

Am I misreading this message?  On future versions if I try to run this tool under a headless system, will it crash?

**Comment by AmitBM** [comment]
Hi Steve132,

We have updated the README.md, hopefully that makes things clearer - give it a look.

If you are using a specific RGA release, please also refer to its accompanying Release Notes PDF file for additional information.

**Comment by AmitBM** [comment]
Hi @Steve132, 

Thanks for explaining your use case.

There is no plan to deprecate RGA's offline modes.
