### ISSUE TITLE
Error: failed to invoke the DX12 backend.

### ISSUE THREAD

**Issue by AdamJMiles** [GPUOpen-Tools/radeon_gpu_analyzer#59]
When the primary display is plugged into a GPU other than an AMD GPU, RGA will emit the following error:

G:\Downloads\rga-windows-x64-2.3>rga -s dx12 -c Bonaire --cs H:\product.txt --cs-model cs_6_3 --cs-entry main --isa H:\isa.txt

Building for Bonaire...
Error: failed to invoke the DX12 backend.
Error: cannot retrieve the list of targets supported by the driver.
failed.

This error occurs when multiple GPUs are present in the system and the primary display is not attached to the AMD GPU.

Please update RGA to enumerate available adapters and pick the AMD one in preference to NVIDIA or Intel GPUs - or report an error indicative of the fact that an AMD GPU is present but not currently the 'main' adapter.

**Comment by AmitBM** [comment]
Hi AdamJMiles,

Thank you for reporting this issue - we will look into that.

**Comment by AmitBM** [comment]
Hi AdamJMiles,

The latest release (RGA 2.5) addresses this issue. The tool will iterate over the system's display adapters and use the first AMD adapter.

Please let us know if your issue is resolved, and thanks again for reporting this.
