### ISSUE TITLE
Parent folder is being littered

### ISSUE THREAD

**Issue by robinchrist** [GPUOpen-Tools/radeon_gpu_analyzer#61]
The `Prebuild` (or rather `FetchDependencies.py`) script places the fetched dependencies in the parent folder of the RGA source directory.
 
Go to `~/dev/radeon_gpu_analyzer/Build/`, run `./Prebuild.sh` -> Dependencies are placed in `~/dev/Common/` - A library should never litter parent directories unless specifically being instructed to do so.

Even if this is a wontfix there should at least be a note in the documentation.

**Comment by AmitBM** [comment]
Hi @robinchrist,

This has been resolved with the update prebuild functionality. The dependencies are fetched into subfolders.
