### ISSUE TITLE
Missing support for SPIR-V 1.5

### ISSUE THREAD

**Issue by simondeschenes** [GPUOpen-Tools/radeon_gpu_analyzer#65]
With Vulkan 1.2 came a new revision of SPIR-V, revision 1.5.

Currently RGA doesn't support shaders compiled to that version and seem to only support shader compiled as SPIR-V 1.3.

Vulkan 1.2 is required to support SPIR-V from 1.0 to 1.5. However, it makes sense for new shader development to target the latest version of SPIR-V which reduces the number of extensions that need to be declared in a SPIR-V module and seems to brings fixes over the previous revisions.

It would be very appreciated if RGA was updated to support the latest version of SPIR-V.

**Comment by AmitBM** [comment]
Hi simondeschenes,

Are you referring to the Vulkan live driver mode (-s vulkan) or the Vulkan offline modes?

**Comment by simondeschenes** [comment]
I am using the offline mode.

**Comment by AmitBM** [comment]
simondeschenes,

Thanks for the details.
SPIR-V 1.5 support would be added in Vulkan offline mode in a future RGA release.

**Comment by AmitBM** [comment]
Hi simondeschenes,

Do you still observe this issue with the latest release (version 2.4)?

**Comment by simondeschenes** [comment]
issue solved
