### ISSUE TITLE
OpenCL: Add support for AMD Radeon RX Vega M GL and AMD Radeon RX Vega M GH

### ISSUE THREAD

**Issue by lmatusz** [GPUOpen-Tools/radeon_gpu_analyzer#66]
Hello,

I really appreciate your work. It would be nice to see support for:
AMD Radeon RX Vega M GL,
AMD Radeon RX Vega M GH

Here are some links:
https://www.techpowerup.com/gpu-specs/radeon-rx-vega-m-gl.c3061
https://www.techpowerup.com/gpu-specs/radeon-rx-vega-m-gh.c3056

Both are Polaris 22, 14 nm, VegaM XL variant. For example GL version "features 1280 shading units, 80 texture mapping units, and 32 ROPs, . AMD has paired 4 GB HBM2 memory with the Radeon RX Vega M GL, which are connected using a 1024-bit memory interface. The GPU is operating at a frequency of 931 MHz, which can be boosted up to 1011 MHz, memory is running at 700 MHz. "

Some more notes about AMD Radeon RX Vega M GL:
Core i5-8305G
Core i7-8705G
Codename: VegaM (Iceland Refresh)
CLRX Version: GCN 1.2
Graphics/Compute: GFX8 (gfx804)
Display Core Engine: 11.2
Unified Video Decoder: 6.3
Video Compression Engine: 3.4

**BTW which Target GPU can I use as workaround for not having gfx804 in RGA?**

**Comment by AmitBM** [comment]
Hi lmatusz,

Thanks for reporting this issue. 

Until the next release, you can use Ellesmere (gfx803) as the target. The compiler treats gfx804 as gfx803.

What mode of RGA are you using specifically?

**Comment by lmatusz** [comment]
Hello,

regarding your question I am going to use it for OpenCL.
BTW what version of OpenCL does RGA support ?

Thanks for quick response and great project.
Lukasz

**Comment by AmitBM** [comment]
Hi lmatusz,

Support for gfx804 (AMD Radeon RX Vega M GL, AMD Radeon RX Vega M GH) should be included in the next RGA release.

**Comment by lmatusz** [comment]
Any news for OpenCL for AMD Radeon RX Vega M GL, AMD Radeon RX Vega M GH embedded GPU ?

**Comment by AmitBM** [comment]
Hi lmatusz,

The next RGA release will include a refresh of the OpenCL mode that would add support for the targets that you mentioned.
In addition, it will include support for RDNA and RDNA2 targets, live VGPR analysis and CFG generation for OpenCL kernels.

The release is expected to happen this month.

**Comment by AmitBM** [comment]
Hi lmatusz,

The updated OpenCL mode in RGA 2.5 (latest release) supports the targets that are mentioned in this thread.
