### ISSUE TITLE
Support for gfx1010 in ROCm-OpenCL mode

### ISSUE THREAD

**Issue by qinapps** [GPUOpen-Tools/radeon_gpu_analyzer#67]
Hi,

I really love this tool, is it planed to support the gfx1010 (in the dropdown menu I can see only gfx906 as newest)

**Comment by AmitBM** [comment]
Hi qinapps,

Assuming that you are referring to the OpenCL mode in the GUI app - 
We plan to update this mode to support RDNA targets, but there is no ETA for this feature yet.

**Comment by qinapps** [comment]
Hi AmitBM,

thx for your answer, lets hope that will be soon )

**Comment by AmitBM** [comment]
Hi qinapps,

The latest release (RGA 2.5) includes support for gfx1010 as well as other RDNA, CDNA and RDNA2 targets.
