### ISSUE TITLE
Use of outdated VK enums

### ISSUE THREAD

**Issue by janisozaur** [GPUOpen-Tools/radeon_gpu_analyzer#69]
https://github.com/GPUOpen-Tools/radeon_gpu_analyzer/blob/44168d942966ff10e446b00b53574e96e605356f/RadeonGPUAnalyzerGUI/Src/rgPipelineStateModelVulkan.cpp#L677-L678
https://github.com/GPUOpen-Tools/radeon_gpu_analyzer/blob/44168d942966ff10e446b00b53574e96e605356f/RadeonGPUAnalyzerGUI/Src/rgPipelineStateModelVulkan.cpp#L651

`VK_ACCESS_COMMAND_PROCESS_READ_BIT_NVX`, `VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX` and `VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX` were removed in 1.2.135 (https://github.com/KhronosGroup/Vulkan-Headers/commit/26341b4bf0bfe481de1acb7020cb09ddb24e6225) but persist here.

**Comment by AmitBM** [comment]
Hi janisozaur,

A fix for this issue was pushed today. Thank you for reporting this.
