### ISSUE TITLE
Support for RX5600

### ISSUE THREAD

**Issue by pmathia0** [GPUOpen-Tools/radeon_gpu_analyzer#72]
Could you please add support for RX5600?

**Comment by AmitBM** [comment]
Hi pmathia0,

RX5600 will be listed as a supported product by RGA in a future release.
In the meantime, you can use gfx1010 as the target, as this is the relevant architecture for this product.

**Comment by AmitBM** [comment]
Hi pmathia0,

This should be resolved in version 2.4 (released today).

**Comment by pmathia0** [comment]
thank you! I noticed that. I guess this can be closed now?
