### ISSUE TITLE
Support for 6800 in GUI (OpenCL Mode)

### ISSUE THREAD

**Issue by qinapps** [GPUOpen-Tools/radeon_gpu_analyzer#76]

**Comment by qinapps** [comment]
in OpenCL mode in the GUI app ist Rona and rdna2 not supported. are there some plans?

**Comment by AmitBM** [comment]
Hi qinapps,

The latest release (RGA 2.5) includes support for the AMD Radeon RX 6800 as well as other RDNA, CDNA and RDNA2 targets in OpenCL mode.
