### ISSUE TITLE
Crash/Freeze on very simple usage, then application stops working forever

### ISSUE THREAD

**Issue by reduz** [GPUOpen-Tools/radeon_gpu_analyzer#78]
Tested on Both Linux and windows, version from 2020-11-19, paste the following shader in frag and build of Radeon GPU Analyzer, you get instafreeze.
Maybe not always the first time, but try a few more times and its warranted to happen.

https://pastebin.com/2dPjFkHr

What is worse, subsequent attempts to use the application result in freezes, or a giant build window and the app becomes forever unusable unless I go to AppData and delete configuration.

**Comment by AmitBM** [comment]
Hi reduz,

Thanks for reporting this issue - a fix will be provided in an upcoming release.

**Comment by AmitBM** [comment]
Hi reduz,

RGA 2.4.1 (released today) contains performance improvements for better handling of shaders with large disassembly.

Can you please give it a shot and confirm that it resolved this issue?

**Comment by AmitBM** [comment]
Fixed in version 2.4.1.
