### ISSUE TITLE
amdspv: Fail to load SPIR-V generator.

### ISSUE THREAD

**Issue by expenses** [GPUOpen-Tools/radeon_gpu_analyzer#81]
I'm trying to run the `vk-spv-offline` compiler from [2.4.1](https://github.com/GPUOpen-Tools/radeon_gpu_analyzer/releases/tag/2.4.1) like so:
```
env PATH=. ./rga-bin -s vk-spv-offline -c Baffin --isa isa.txt path/to/shader.spv
```
I get the following output:
```
Target GPU detected:

Baffin (Graphics IP v8)
	AMD Radeon (TM) E9260
	AMD Radeon Pro 465
	RX 560X
	Radeon (TM) Pro V5300X
	Radeon (TM) Pro WX 4100
	Radeon (TM) Pro WX Series
	Radeon 550 Series
	Radeon Pro Series
	Radeon RX 560 Series
	Radeon RX550/550 Series
	Radeon(TM) RX 460 Graphics

Building for Baffin... failed.
Error: Fail to load SPIR-V generator.
```
When ran with `-v`, the above command reveals that it attempts to run
`
amdspv -Dall -l -gfxip 8 -set in.spv="/path/to/shader.spv" out.comp.isa="/home/ashley/.rga/GPUOpen/rga/baffin_isaBaffin208233_comp.amdisa" out.vert.isa="/home/ashley/.rga/GPUOpen/rga/baffin_isaBaffin208233_vert.amdisa" out.tesc.isa="/home/ashley/.rga/GPUOpen/rga/baffin_isaBaffin208233_tesc.amdisa" out.tese.isa="/home/ashley/.rga/GPUOpen/rga/baffin_isaBaffin208233_tese.amdisa" out.geom.isa="/home/ashley/.rga/GPUOpen/rga/baffin_isaBaffin208233_geom.amdisa" out.frag.isa="/home/ashley/.rga/GPUOpen/rga/baffin_isaBaffin208233_frag.amdisa" out.comp.isaText="baffin_x_comp.amdisa" out.vert.isaText="baffin_x_vert.amdisa" out.tesc.isaText="baffin_x_tesc.amdisa" out.tese.isaText="baffin_x_tese.amdisa" out.geom.isaText="baffin_x_geom.amdisa" out.frag.isaText="baffin_x_frag.amdisa" out.glslLog="/home/ashley/.rga/amdspvTempFile.txt" defaultOutput=0 -set val=0
`
and that is what is giving me the `Fail to load SPIR-V generator.` error. As `amdspv` appears to be a closed-source binary, I don't have an easy way of debugging this.

OS: Arch Linux x86_64 5.11.2-arch1-1
GPU: Intel UHD Graphics 630 (I'm running an offline compiler, so it shouldn't matter that I'm not running an AMD card, right?)

**Comment by AmitBM** [comment]
Hi expenses,

Did you add the utils subfolder to LD_LIBRARY_PATH? It seems like the loader cannot find spvgen.so.

Note that you are trying to run the rga executable binary (rga-bin) directly, while we created a script (rga) that sets up the environment automatically for you. Try running rga instead of rga-bin.

**Comment by expenses** [comment]
That fixed it, thanks!
