### ISSUE TITLE
Is the tools suitable for ARM CPU？

### ISSUE THREAD

**Issue by yushan107** [GPUOpen-Tools/radeon_gpu_analyzer#85]

**Comment by AmitBM** [comment]
Hi @yushan107,

The Radeon GPU Analyzer (RGA) is an offline compiler and code analysis tool for Vulkan, DirectX, OpenGL, and OpenCL. It supports a variety of AMD GPU architectures as the compilation target.

ARM CPU or CPU support in general is out of scope for RGA at this time.
