### ISSUE TITLE
Which AMDVLK version does RGA use?

### ISSUE THREAD

**Issue by ishitatsuyuki** [GPUOpen-Tools/radeon_gpu_analyzer#89]
I'm getting weird generated code from RGA, and I'm confused because it does not match the output of amdllpc downloaded from https://github.com/GPUOpen-Drivers/AMDVLK/releases. Notably, it straight out ignores any SPIR-V loop unroll annotations, and I'm guessing the bundled AMDVLK is not at all the same thing as the open-source driver.

Meanwhile, RGA also refuses to load AMDVLK packaged by my distro (Arch Linux), saying that it is "unable to extract the list of supported devices".

What pipeline compiler/AMDVLK are you bundling with RGA? Is that the proprietary pipeline compiler?

**Comment by AmitBM** [comment]
Hi ishitatsuyuki,

RGA has the latest public closed-source driver bundled with it (at the time of release). You seem to be referring to the open-source driver. The two drivers use a different compiler.
