### ISSUE TITLE
Support various shader extensions for OpenGL

### ISSUE THREAD

**Issue by AquaGeneral** [GPUOpen-Tools/radeon_gpu_analyzer#92]
Currently it's not possible for me to use the Radeon GPU Analyzer since I am going to be utilising a lot of subgroup intrinsics made available through the [KHR_shader_subgroup](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_shader_subgroup.txt) extension. Currently RGA just seems to run its virtual OpenGL context with no extra extensions registered--meaning this will be a problem for many other extensions too.

**Comment by AmitBM** [comment]
Hi AquaGeneral,

Version 2.6.2 (released today) contains a new offline compiler for OpenGL.

Please give it a shot and let us know if you still experience issues compiling shaders that use any extensions.

**Comment by AquaGeneral** [comment]
> Hi AquaGeneral,
> 
> Version 2.6.2 (released today) contains a new offline compiler for OpenGL.
> 
> Please give it a shot and let us know if you still experience issues compiling shaders that use any extensions.

I've tested this on a bunch of shaders and it seems to be working perfectly! Thanks very much for getting this fixed.

**Comment by BoyBaykiller** [comment]
Using RGA 2.6.2 the name of the following extensions are defined even though the RX 5700 XT I am running this on doesnt support them.

* `GL_NV_compute_shader_derivatives`
* `GL_NV_shading_rate_image`
* `GL_NV_viewport_array2`

Example:
```glsl
#version 460 core
#extension GL_NV_compute_shader_derivatives : enable

#ifdef GL_NV_compute_shader_derivatives 
// code in here is supposed to be ignored but it's not
#endif
```
If I run this code through a OpenGL application it behaves as expected.

I assume this is the case for more extensions than the ones I listed.
