### ISSUE TITLE
Extension name defined even if not supported or enabled

### ISSUE THREAD

**Issue by BoyBaykiller** [GPUOpen-Tools/radeon_gpu_analyzer#99]
Using RGA 2.6.2 the name of the following extensions are defined even though the RX 5700 XT I am running this on doesnt support them.

* `GL_NV_compute_shader_derivatives`
* `GL_NV_shading_rate_image`
* `GL_NV_viewport_array2`

Example:
```glsl
#version 460 core

#ifdef GL_NV_compute_shader_derivatives 
// code in here is supposed to be ignored but it's not
#endif
```
If I run this code through a OpenGL application it behaves as expected.

I assume this is the case for more extensions than the ones I listed.

**Comment by BoyBaykiller** [comment]
I noticed these extensions were added in the recent driver release 22.7.1. As far as this goes this issue can be closed.

I have a question about `GL_NV_shading_rate_image` though.
Why can I use glsl functionality from this extension but can't load the functions introduced by it.
Are client side functions like `BindShadingRateImageNV` not implemented yet?

**Comment by AmitBM** [comment]
`GL_NV_compute_shader_derivatives `should be supported by the driver soon.
There is no plan for supporting `GL_NV_shading_rate_image` and `GL_NV_viewport_array2 `. These should have been disabled in the driver - will be fixed in a future driver release.
